planetlabs/gpq

cmd/gpq/version.go

This adds a `gpq version` command for printing the `gpq` version (not the GeoParquet version).

Add command for printing the version

---

readme.md

typo fix on brew

---

cmd/gpq/describe.go
cmd/gpq/main.go
readme.md

This adds a `gpq describe` command to print information about a GeoParquet file.

Command to print information about a GeoParquet file

---

cmd/gpq/convert.go
cmd/wasm/main.go
internal/geojson/geojson.go
internal/geojson/geojson_test.go
internal/geojson/schema.go
internal/geojson/schema_test.go
internal/geojson/testdata/sparse-properties.geojson
readme.md

Previously, one feature at a time would be considered when building a Parquet schema from GeoJSON.  This meant that feature collections with "sparse" properties (lots of nulls or missing properties in some features) could not reliably be converted to GeoParquet.
With this change, the `convert` command takes `--min` and `--max` arguments to control the minimum and maximum number of GeoJSON features to consider when building a schema.  The schema is incrementally built using at least `min` features, and efforts to build a complete schema continue until `max` features.

Incrementally build converters and schema

---

cmd/gpq/describe.go
cmd/wasm/main.go
internal/geojson/geojson.go
internal/geojson/geojson_test.go
internal/geojson/metadata.go
internal/geoparquet/geoparquet.go
internal/geoparquet/geoparquet_test.go
internal/validator/validator.go

This adds support for WKT encoded geometries.
Although the spec doesn't currently allow it, if `"encoding": "WKT"` metadata is included for a geometry column, the data will be read as WKT.
In addition, if no `encoding` metadata property is found for a geometry column, the encoding will be derived from the column type.  For columns annotated with the string logical type, WKT will be assumed.  For other byte arrays (with no string annotation), WKB will be assumed.

Support WKT encoding and use column type when encoding is unknown

---

internal/geojson/geojson.go
internal/geojson/geojson_test.go

This makes it so the defaults are used for minFeatures, maxFeatures, and compression when converting to GeoParquet from GeoJSON.

Allow limited converter options

---

cmd/gpq/convert.go
internal/geojson/geojson.go

We have run into cases where support for reading ZSTD compressed Parquet is limited.  For tools like GDAL, this depends on the version of arrow-cpp that it was built with (and potentially which ZSTD related options).
This change updates the default compression to be `gzip` instead of `zstd`.  It is still possible to get ZSTD by passing `--compression zstd` to the `gpq convert` command.

Use gzip by default

---

cmd/gpq/convert.go
internal/geojson/geojson.go
internal/geoparquet/geoparquet.go
internal/geoparquet/geoparquet_test.go
internal/validator/rules.go
internal/validator/validator.go

This adds support for converting Parquet files without "geo" file metadata to GeoParquet files.
```bash
gpq convert non-geo.parquet geo.parquet
```
For this to work, the non-geo Parquet file must have a column named "geometry" with WKT or WKB encoded geometries.

Convert Parquet without metadata to GeoParquet

---

internal/geoparquet/geoparquet.go
internal/geoparquet/geoparquet_test.go
readme.md

Previously, when converting an input Parquet file to a GeoParquet file, the same metadata struct would be used to read the input metadata and write the output metadata.  When the input geometry type is WKT, the output is converted to WKB.  During writing, the metadata was modified after writing the first geometry.  This meant that reading the second geometry failed since it was not WKB (but the modified metadata indicated that it was).
This change ensures that the input metadata is cloned before creating modified output metadata.
Fixes #34.

Fix issue converting Parquet with WKT geometry

---

cmd/gpq/convert.go
internal/geoparquet/geoparquet.go
internal/geoparquet/geoparquet_test.go
readme.md

This adds an `--input-primary-column` argument to the `convert` command.  When reading a Parquet file without "geo" metadata, the primary geometry column defaults to `geometry`.  The new argument can be used to change this.
```shell
gpq convert --input-primary-column geom example.parquet example.geoparquet
```
Fixes #33.

Accept an alternative primary column name when reading Parquet

---

cmd/gpq/describe.go
go.mod
go.sum
internal/geoparquet/geoparquet.go
internal/geoparquet/geoparquet_test.go

This adds additional information to the describe output:
* geometry column crs (name / id)
* number of rows
* geoparquet version
The edges, orientation, and crs per geometry column is summarized in a "detail" column in the text output.  Number of rows and version are shown in the table footer.  The primary geometry column name is shown in bold.
```shell
╭────────────┬──────────────┬────────────┬────────────┬──────────┬───────────────────────┬───────────────────────────┬──────────────────────────╮
│ COLUMN     │ TYPE         │ ANNOTATION │ REPETITION │ ENCODING │ GEOMETRY TYPES        │ BOUNDS                    │ DETAIL                   │
├────────────┼──────────────┼────────────┼────────────┼──────────┼───────────────────────┼───────────────────────────┼──────────────────────────┤
│ …
```

Additional information in describe output

---

web/main.js

This makes it so the WASM converter accepts `.geoparquet` files as well as `.parquet`.
Fixes #53.

Allow .geoparquet extension

---

cmd/gpq/convert.go
cmd/gpq/describe.go
internal/geoparquet/geoparquet.go
internal/pqutil/parquet.go
internal/pqutil/transform.go
internal/pqutil/transform_test.go
internal/validator/validator_test.go

This adds information about the column compression in the `describe` output.  For the `--format json` output, compression detail is provided on nested fields.  For the non-JSON output, only the top level fields are described.  And the compression is only reported based on columns in the first row group.
This also fixes an issue where Parquet to GeoParquet compression changes would only work when the input data was uncompressed.
Fixes #46.
Fixes #47.

Report on compression in describe output

---

cmd/gpq/command/command.go
cmd/gpq/command/command_test.go
cmd/gpq/command/convert.go
cmd/gpq/command/convert_test.go
cmd/gpq/command/describe.go
cmd/gpq/command/describe_test.go
cmd/gpq/command/validate.go
cmd/gpq/command/version.go
cmd/gpq/main.go
internal/geo/geo.go
internal/geoparquet/geoparquet.go
internal/test/test.go
internal/validator/validator.go
internal/validator/validator_test.go

This makes it so the commands optionally read from stdin and write to stdout.
Examples:
```
cat example.parquet | gpq validate
cat example.parquet | gpq describe
cat example.parquet | gpq convert --from geoparquet --to geojson
gpq convert example.geojson --to geoparquet
```
Fixes #78.

Optionally use stdin and stdout for validate, describe, and convert commands

---

cmd/gpq/command/convert.go
internal/geojson/geojson.go
internal/geojson/geojson_test.go
internal/geojson/testdata/ten-points.geojson
internal/geoparquet/geoparquet.go
internal/pqutil/transform.go
internal/pqutil/transform_test.go
internal/test/test.go

This adds a `--row-group-length` argument to the `convert` command.  If not provided, the row group length when reading GeoJSON is `64 * 1024 * 1024`, and when reading Parquet, the row group size of the input is retained.
Fixes #65.

Configurable row group length for writing

---

go.mod
go.sum

This temporarily replaces the Arrow dependency with the fix in https://github.com/apache/arrow/pull/37785 - making it possible to read Parquet files with all null values on ARM64 devices.
Fixes #57.

Use patch for ARM64 assembly bitmap extraction

---

internal/geoparquet/geoparquet.go
internal/pqutil/transform.go
internal/validator/rules.go
internal/validator/testdata/complex-types/expected.json
internal/validator/testdata/complex-types/input.json
internal/validator/validator_test.go

This addresses a couple issues when transforming Parquet to GeoParquet.  Previously, the `version` would not always be included in the `geo` key/value metadata.  In addition, Parquet with logical fields that were represented by multiple physical columns would not validate after being transformed to GeoParquet.

Ensure that Parquet with complex types transforms to valid GeoParquet

---

cmd/gpq/command/describe.go
cmd/gpq/command/describe_test.go
internal/pqutil/transform_test.go
internal/test/test.go

This adds output to the `describe` command that suggests running `validate` if the geo metadata is invalid.
Example output:
```shell
╭──────────┬────────┬────────────┬────────────┬─────────────╮
│ COLUMN   │ TYPE   │ ANNOTATION │ REPETITION │ COMPRESSION │
├──────────┼────────┼────────────┼────────────┼─────────────┤
│ geoid    │ binary │ string     │ 0..1       │ snappy      │
│ geometry │ binary │            │ 0..1       │ snappy      │
├──────────┼────────┴────────────┴────────────┴─────────────┤
│ Rows     │ 3233                                           │
╰──────────┴────────────────────────────────────────────────╯
⚠️  Not a valid GeoParquet file (invalid "geo" metadata). Run describe with the --metadata-only flag 
to see the "geo" metadata value. Run validate for more detail on …
```

Suggest running validate if metadata parsing fails in describe

---

cmd/gpq/command/describe.go
cmd/gpq/command/describe_test.go

This adds a row group count to the `describe` output.
I didn't summarize the number of rows per group.  Might revisit that later.
Fixes #83.

Include the row group count in describe output

---

cmd/gpq/command/command.go
cmd/gpq/command/command_test.go
cmd/gpq/command/convert.go
cmd/gpq/command/convert_test.go
cmd/gpq/command/describe.go
cmd/gpq/command/describe_test.go
cmd/gpq/command/validate.go
internal/storage/http.go
internal/storage/http_test.go
internal/storage/storage.go

This adds support for using URLs in addition to file paths as the input for the `describe`, `validate`, and `convert` commands.
```shell
╭────────────────────┬────────┬────────────┬────────────┬─────────────┬──────────┬───────────────────────┬───────────────────────────┬──────────────────────────╮
│ COLUMN             │ TYPE   │ ANNOTATION │ REPETITION │ COMPRESSION │ ENCODING │ GEOMETRY TYPES        │ BOUNDS                    │ DETAIL                   │
├────────────────────┼────────┼────────────┼────────────┼─────────────┼──────────┼───────────────────────┼───────────────────────────┼──────────────────────────┤
│ pop_est            │ double │            │ 0..1       │ snappy      │          │                       │                           │                          │
│ continent …
```

Accept URLs for describe, validate, and convert input

---

.github/workflows/test.yml

The right fix here is to figure out why the cache isn't working, but I'll save that for later.
Perhaps related https://github.com/golangci/golangci-lint-action/issues/863.

Increase timeout for golangci-lint-action

---

internal/geoparquet/geoparquet.go
internal/pqutil/transform.go
internal/pqutil/transform_test.go
internal/validator/validator_test.go

This updates the Parquet transform-by-column code to use the `pqarrow.FileWriter` instead of a `file.Writer`.  When using the `file.Writer`, I'm seeing some cases where invalid Parquet is generated (see https://github.com/apache/arrow/issues/38503).
Fixes #102.

Use the pqarrow file writer

---

internal/geo/geo.go
internal/validator/testdata/bad-crs-type/expected.json
internal/validator/testdata/with-empty-geometry/expected.json
internal/validator/testdata/with-empty-geometry/input.json
internal/validator/testdata/with-null-geometry/expected.json
internal/validator/testdata/with-null-geometry/input.json
internal/validator/validator.go
internal/validator/validator_test.go

Currently, if you run `gpq validate` against a Parquet file that has nulls for WKB encoded geometries, the program panics (see #188).  This addresses that.

Allow empty and null geometries in validation
